"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Swal from "sweetalert2";
import { loadPortalPermissions, type PermissionEntry } from "@/lib/utils/portalPermissions";
import { CoachingSession, MidCycleReview, MonitoringCase, MonitoringUpdate, command, downloadEvidence,
  getCase, getReview, getSessions, listMine, monitoringError, uploadEvidence } from "@/lib/services/performanceMonitoring";
import styles from "./MyPerformanceMonitoring.module.scss";

const root = "/api/primehr/v1/performance-management";
const requestKey = () => crypto.randomUUID();
const today = () => new Date().toISOString().slice(0, 10);
const versionCommand = (recordVersion: number, employeeResponse?: string) => ({ recordVersion, idempotencyKey: requestKey(), reason: null, employeeResponse: employeeResponse || null, overrideWindow: false });
const emptyUpdate = { itemId: "", reportingDate: today(), narrativeAccomplishment: "", accomplishedValue: "", progressPercent: "", issuesRisks: "", supportNeeded: "", employeeRemarks: "" };

export default function MyPerformanceMonitoring() {
  const [monitoringPermission, setMonitoringPermission] = useState<PermissionEntry>({}); const [coachingPermission, setCoachingPermission] = useState<PermissionEntry>({});
  const [cases, setCases] = useState<MonitoringCase[]>([]); const [selected, setSelected] = useState<MonitoringCase | null>(null);
  const [sessions, setSessions] = useState<CoachingSession[]>([]); const [review, setReview] = useState<MidCycleReview | null>(null);
  const [draft, setDraft] = useState(emptyUpdate); const [editing, setEditing] = useState<MonitoringUpdate | null>(null);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { try { setError(""); setCases(await listMine()); } catch (reason) { setError(monitoringError(reason)); } }, []);
  useEffect(() => { void loadPortalPermissions(true).then(value => { setMonitoringPermission(value.isAdministrator ? { canAccess: true, canAdd: true, canEdit: true, canSubmit: true, canApprove: true } : value.permissionData["primehr.performance-monitoring"] ?? {}); setCoachingPermission(value.isAdministrator ? { canAccess: true, canAdd: true, canEdit: true, canSubmit: true, canApprove: true } : value.permissionData["primehr.performance-coaching"] ?? {}); void load(); }); }, [load]);
  async function open(id: string) { setBusy(true); setError(""); try { const detail = await getCase(id); setSelected(detail); setEditing(null); setDraft({ ...emptyUpdate, itemId: detail.items[0]?.id ?? "" }); if (coachingPermission.canAccess) { setSessions(await getSessions(id)); try { setReview(await getReview(id)); } catch (reason) { if (!(reason instanceof Error) || !reason.message.toLowerCase().includes("not found")) setError(monitoringError(reason)); else setReview(null); } } } catch (reason) { setError(monitoringError(reason)); } finally { setBusy(false); } }
  async function mutate<T>(work: () => Promise<T>, success: string) { setBusy(true); setError(""); try { await work(); setMessage(success); await load(); if (selected) await open(selected.id); } catch (reason) { setError(monitoringError(reason)); } finally { setBusy(false); } }
  function body() { return { commitmentItemId: draft.itemId, reportingDate: draft.reportingDate, narrativeAccomplishment: draft.narrativeAccomplishment, accomplishedValue: draft.accomplishedValue ? Number(draft.accomplishedValue) : null, progressPercent: draft.progressPercent ? Number(draft.progressPercent) : null, issuesRisks: draft.issuesRisks || null, supportNeeded: draft.supportNeeded || null, employeeRemarks: draft.employeeRemarks || null }; }
  async function saveUpdate(event: FormEvent) { event.preventDefault(); if (!selected) return; const payload = body(); await mutate(() => editing ? command(`${root}/monitoring-updates/${editing.id}`, { ...payload, recordVersion: editing.recordVersion }, "PUT") : command(`${root}/monitoring-cases/${selected.id}/updates`, { ...payload, idempotencyKey: requestKey() }), editing ? "Progress draft updated." : "Progress draft created."); setEditing(null); setDraft({ ...emptyUpdate, itemId: selected.items[0]?.id ?? "" }); }
  function editUpdate(update: MonitoringUpdate) { setEditing(update); setDraft({ itemId: update.itemId, reportingDate: update.reportingDate, narrativeAccomplishment: update.narrativeAccomplishment, accomplishedValue: update.accomplishedValue?.toString() ?? "", progressPercent: update.progressPercent?.toString() ?? "", issuesRisks: update.issuesRisks ?? "", supportNeeded: update.supportNeeded ?? "", employeeRemarks: update.employeeRemarks ?? "" }); }
  async function submitUpdate(update: MonitoringUpdate) { const confirmation = await Swal.fire({ title: "Submit this progress update?", text: "The submitted revision is preserved in history.", icon: "question", showCancelButton: true }); if (!confirmation.isConfirmed) return; await mutate(() => command(`${root}/monitoring-updates/${update.id}/submit`, versionCommand(update.recordVersion)), "Progress update submitted to your supervisor."); }
  async function correctUpdate(update: MonitoringUpdate) { editUpdate(update); const confirmation = await Swal.fire({ title: "Create a correction?", text: "Saving creates a new revision and preserves the prior submission.", icon: "info", showCancelButton: true }); if (!confirmation.isConfirmed) { setEditing(null); return; } setEditing({ ...update, status: "CORRECTION" }); }
  async function saveCorrection(event: FormEvent) { event.preventDefault(); if (!editing) return; await mutate(() => command(`${root}/monitoring-updates/${editing.id}/corrections`, { ...body(), idempotencyKey: requestKey() }), "Correction draft created with prior history preserved."); setEditing(null); }
  async function addEvidence(update: MonitoringUpdate, file: File | null) { if (!file) return; await mutate(() => uploadEvidence(update.id, file), "Evidence uploaded securely."); }
  async function voidEvidence(id: string, recordVersion: number) { const response = await Swal.fire({ title: "Void evidence?", input: "textarea", inputLabel: "Required reason", showCancelButton: true, inputValidator: (value: string) => value.trim() ? undefined : "A reason is required." }); if (!response.isConfirmed) return; await mutate(() => command(`${root}/monitoring-evidence/${id}/void`, { recordVersion, idempotencyKey: requestKey(), reason: response.value, overrideWindow: false }), "Evidence voided; audit history was retained."); }
  async function submitAccomplishments() { if (!selected) return; const confirmation = await Swal.fire({ title: "Submit final accomplishments?", text: "All required updates and evidence must be ready. The accomplishment set will be frozen for supervisor review.", icon: "question", showCancelButton: true }); if (!confirmation.isConfirmed) return; await mutate(() => command(`${root}/monitoring-cases/${selected.id}/accomplishments/submit`, versionCommand(selected.recordVersion)), "Final accomplishments submitted."); }
  async function acknowledgeSession(session: CoachingSession) { const response = await Swal.fire({ title: "Acknowledge coaching session", input: "textarea", inputLabel: "Optional response", text: "Acknowledgment confirms receipt only; it does not mean agreement.", showCancelButton: true }); if (!response.isConfirmed) return; await mutate(() => command(`${root}/coaching-sessions/${session.id}/acknowledge`, versionCommand(session.recordVersion, String(response.value ?? ""))), "Coaching session receipt acknowledged."); }
  async function updateAction(id: string, recordVersion: number, completed: boolean) { const response = await Swal.fire({ title: completed ? "Complete action item" : "Update action item", input: "textarea", inputLabel: "Progress note", showCancelButton: true, inputValidator: (value: string) => value.trim() ? undefined : "A progress note is required." }); if (!response.isConfirmed) return; await mutate(() => command(`${root}/coaching-action-items/${id}`, { progressNote: response.value, completed, recordVersion, idempotencyKey: requestKey() }, "PUT"), completed ? "Action item marked completed for supervisor verification." : "Action-item progress updated."); }
  async function acknowledgeReview() { if (!review) return; const response = await Swal.fire({ title: "Acknowledge mid-cycle review", input: "textarea", inputLabel: "Employee narrative / response", text: "Acknowledgment confirms receipt only.", showCancelButton: true }); if (!response.isConfirmed) return; await mutate(() => command(`${root}/mid-cycle-reviews/${review.id}/acknowledge`, { recordVersion: review.recordVersion, idempotencyKey: requestKey(), reason: null, employeeNarrative: String(response.value ?? "") }), "Mid-cycle review receipt acknowledged."); }
  const active = selected?.status === "OPEN" || selected?.status === "RETURNED";
  return <div className={styles.page}><h1>My Performance Monitoring</h1><p className={styles.lead}>Your identity and records come from your authenticated account. You cannot select or access another employee.</p>{message && <div className={styles.notice}>{message}</div>}{error && <div className={styles.error}>{error}</div>}
    <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Form</th><th>Supervisor</th><th>Status</th><th>Action</th></tr></thead><tbody>{cases.length ? cases.map(item => <tr key={item.id}><td>{item.formType}</td><td>{item.supervisorEmployeeNo}</td><td>{item.status}</td><td><button onClick={() => void open(item.id)}>Open</button></td></tr>) : <tr><td colSpan={4}>No performance monitoring case is available for your account.</td></tr>}</tbody></table></div>
    {selected && <><h2>{selected.formType} Monitoring</h2><p className={styles.summary}>Status <strong>{selected.status}</strong> · supervisor {selected.supervisorEmployeeNo} · version {selected.recordVersion}</p>{selected.returnReason && <div className={styles.error}>Returned for correction: {selected.returnReason}</div>}
      {active && (monitoringPermission.canAdd || monitoringPermission.canEdit) && <form className={styles.form} onSubmit={editing?.status === "CORRECTION" ? saveCorrection : saveUpdate}><label>Approved commitment item<select required disabled={Boolean(editing)} value={draft.itemId} onChange={e => setDraft({ ...draft, itemId: e.target.value })}>{selected.items.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Reporting date<input required type="date" value={draft.reportingDate} onChange={e => setDraft({ ...draft, reportingDate: e.target.value })} /></label><label>Progress percent<input min="0" max="100" step="0.0001" type="number" value={draft.progressPercent} onChange={e => setDraft({ ...draft, progressPercent: e.target.value })} /></label><label className={styles.wide}>Accomplishment<textarea required value={draft.narrativeAccomplishment} onChange={e => setDraft({ ...draft, narrativeAccomplishment: e.target.value })} /></label><label>Accomplished value<input type="number" step="any" value={draft.accomplishedValue} onChange={e => setDraft({ ...draft, accomplishedValue: e.target.value })} /></label><label>Issues / risks<textarea value={draft.issuesRisks} onChange={e => setDraft({ ...draft, issuesRisks: e.target.value })} /></label><label>Support needed<textarea value={draft.supportNeeded} onChange={e => setDraft({ ...draft, supportNeeded: e.target.value })} /></label><label>Employee remarks<textarea value={draft.employeeRemarks} onChange={e => setDraft({ ...draft, employeeRemarks: e.target.value })} /></label><div className={styles.actions}><button disabled={busy}>{editing?.status === "CORRECTION" ? "Create correction" : editing ? "Save draft" : "Add progress draft"}</button>{editing && <button type="button" className={styles.secondary} onClick={() => setEditing(null)}>Cancel</button>}</div></form>}
      <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Item / date</th><th>Accomplishment</th><th>Status</th><th>Feedback and evidence</th><th>Controls</th></tr></thead><tbody>{selected.updates.length ? selected.updates.map(update => <tr key={update.id}><td>{selected.items.find(item => item.id === update.itemId)?.label ?? update.itemId}<br />{update.reportingDate}<br />Revision {update.revisionNo}</td><td>{update.narrativeAccomplishment}<br />Progress {update.progressPercent ?? "—"}%</td><td>{update.status}</td><td>{update.feedback.map(item => <div key={item.id}>{item.decision}: {item.feedback || "No note"}</div>)}{update.evidence.map(evidence => <div key={evidence.id}><button onClick={() => void downloadEvidence(evidence)}>{evidence.filename}</button>{evidence.status === "ACTIVE" && monitoringPermission.canEdit && <button className={styles.danger} onClick={() => void voidEvidence(evidence.id, evidence.recordVersion)}>Void</button>}</div>)}</td><td><div className={styles.actions}>{(update.status === "DRAFT" || update.status === "RETURNED") && monitoringPermission.canEdit && <button onClick={() => editUpdate(update)}>Edit</button>}{(update.status === "DRAFT" || update.status === "RETURNED") && monitoringPermission.canSubmit && <button onClick={() => void submitUpdate(update)}>Submit</button>}{["SUBMITTED", "ACCEPTED", "RETURNED"].includes(update.status) && monitoringPermission.canEdit && <button onClick={() => void correctUpdate(update)}>Correct</button>}{active && monitoringPermission.canEdit && <label className={styles.upload}>Evidence<input aria-label={`Evidence ${update.id}`} type="file" accept="application/pdf,image/png,image/jpeg" onChange={e => void addEvidence(update, e.target.files?.[0] ?? null)} /></label>}</div></td></tr>) : <tr><td colSpan={5}>No progress updates yet.</td></tr>}</tbody></table></div>
      {active && monitoringPermission.canSubmit && <div className={styles.actions}><button disabled={busy} onClick={() => void submitAccomplishments()}>Submit final accomplishments</button></div>}
      {coachingPermission.canAccess && <section className={styles.section}><h2>Coaching</h2>{sessions.length ? sessions.map(session => <article className={styles.history} key={session.id}><h3>{session.agenda} · {session.status}</h3><p><strong>Goal:</strong> {session.goal}</p><p><strong>Observed issue:</strong> {session.observedIssue}</p><p><strong>Agreed action:</strong> {session.agreedAction}</p><p><strong>Supervisor feedback:</strong> {session.employeeVisibleFeedback || "—"}</p><p><strong>Your response:</strong> {session.employeeResponse || "—"}</p>{session.privateNotes !== null && <div className={styles.error}>Restricted notes must never be exposed in Employee Portal.</div>}{session.status === "ISSUED" && coachingPermission.canSubmit && <button onClick={() => void acknowledgeSession(session)}>Acknowledge receipt</button>}{session.actionItems.map(item => <div className={styles.actionItem} key={item.id}>{item.description} · due {item.dueDate} · <strong>{item.status}</strong>{["OPEN", "IN_PROGRESS", "REOPENED"].includes(item.status) && coachingPermission.canEdit && <div className={styles.actions}><button onClick={() => void updateAction(item.id, item.recordVersion, false)}>Update progress</button><button onClick={() => void updateAction(item.id, item.recordVersion, true)}>Mark completed</button></div>}</div>)}</article>) : <p>No coaching sessions have been issued.</p>}</section>}
      {coachingPermission.canAccess && review && <section className={styles.section}><h2>Mid-cycle review</h2><p>{review.supervisorNarrative}</p><p className={styles.summary}>Status {review.status} · updates {review.snapshotUpdateCount} · open actions {review.snapshotOpenActionCount} · missing evidence {review.snapshotMissingEvidenceCount}</p>{review.amendmentRecommended && <p>Formal commitment amendment recommended: {review.amendmentReason}</p>}{review.status === "SUBMITTED" && coachingPermission.canSubmit && <button onClick={() => void acknowledgeReview()}>Acknowledge receipt</button>}</section>}
    </>}
  </div>;
}
