"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Swal from "sweetalert2";
import { newSalnDraft, salnApi, type SalnCorrection, type SalnDraft, type SalnRecord, type SalnSummary } from "@/lib/services/saln";
import modalStyles from "@/styles/Modal.module.scss";
import styles from "./SalnWorkspace.module.scss";

const replaceAt=<T,>(rows:T[],index:number,value:T)=>rows.map((row,i)=>i===index?value:row);
const money=(value:string|number)=>Number(value||0).toLocaleString("en-PH",{style:"currency",currency:"PHP"});
const errorText=(error:unknown)=>error instanceof Error?error.message:"The SALN operation could not be completed.";
const previewPdf=async(id:number)=>{try{const blob=await salnApi.pdf(id);const url=URL.createObjectURL(blob);window.open(url,"_blank","noopener,noreferrer");window.setTimeout(()=>URL.revokeObjectURL(url),60_000);}catch(error){await Swal.fire("Unable to generate PDF",errorText(error),"error");}};
const emptyReal=()=>({ownerType:"DECLARANT" as const,ownerName:"",description:"",kind:"",exactLocation:"",assessedValue:"",fairMarketValue:"",acquisitionYear:new Date().getFullYear(),acquisitionMode:"",acquisitionCost:""});
const emptyPersonal=()=>({ownerType:"DECLARANT" as const,ownerName:"",description:"",acquisitionYear:new Date().getFullYear(),acquisitionCost:""});
const emptyLiability=()=>({ownerType:"DECLARANT" as const,ownerName:"",nature:"",creditorName:"",outstandingBalance:""});
const emptyBusiness=()=>({ownerType:"DECLARANT" as const,ownerName:"",entityName:"",businessAddress:"",nature:"",dateAcquired:""});

export default function SalnWorkspace(){
  const [records,setRecords]=useState<SalnSummary[]>([]);const [draft,setDraft]=useState<SalnDraft>(newSalnDraft());
  const [selected,setSelected]=useState<SalnRecord|null>(null);const [corrections,setCorrections]=useState<SalnCorrection[]>([]);
  const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [formOpen,setFormOpen]=useState(false);
  const editable=!selected||selected.status==="DRAFT"||selected.status==="FOR_CORRECTION";
  const loadList=useCallback(async()=>{setLoading(true);try{setRecords(await salnApi.list());}catch(error){await Swal.fire("Unable to load SALNs",errorText(error),"error");}finally{setLoading(false);}},[]);
  useEffect(()=>{void loadList();},[loadList]);
  const open=async(id:number)=>{setLoading(true);try{const record=await salnApi.get(id);setSelected(record);setDraft({...record});setCorrections(record.status==="FOR_CORRECTION"?await salnApi.corrections(id):[]);setFormOpen(true);}catch(error){await Swal.fire("Unable to open SALN",errorText(error),"error");}finally{setLoading(false);}};
  const resetToNew=()=>{setSelected(null);setCorrections([]);setDraft(newSalnDraft());setFormOpen(true);};
  const startNew=async()=>{
    const pristineNew=!selected&&JSON.stringify(draft)===JSON.stringify(newSalnDraft());
    if(formOpen&&pristineNew){await Swal.fire("New SALN ready","The blank SALN form is already open below.","info");return;}
    if(formOpen&&editable){
      const confirmation=await Swal.fire({title:"Start a new SALN?",text:"Any unsaved changes in the current form will be cleared.",icon:"warning",showCancelButton:true,confirmButtonText:"Start new SALN"});
      if(!confirmation.isConfirmed)return;
    }
    resetToNew();
  };
  const setField=<K extends keyof SalnDraft>(key:K,value:SalnDraft[K])=>setDraft(current=>({...current,[key]:value}));
  const computed=useMemo(()=>{const real=draft.realProperties.reduce((sum,row)=>sum+Number(row.acquisitionCost||0),0);const personal=draft.personalProperties.reduce((sum,row)=>sum+Number(row.acquisitionCost||0),0);const liabilities=draft.liabilities.reduce((sum,row)=>sum+Number(row.outstandingBalance||0),0);return {real,personal,assets:real+personal,liabilities,net:real+personal-liabilities};},[draft]);
  const save=async(event:FormEvent)=>{event.preventDefault();setSaving(true);try{const saved=await salnApi.save(draft,selected?.id);setSelected(saved);setDraft({...saved});await loadList();await Swal.fire("Draft saved","Your SALN draft has been saved.","success");}catch(error){await Swal.fire("Unable to save",errorText(error),"error");}finally{setSaving(false);}};
  const submit=async()=>{if(!selected){await Swal.fire("Save first","Save the draft before submitting it.","info");return;}const confirmation=await Swal.fire({title:selected.status==="FOR_CORRECTION"?"Resubmit corrected SALN?":"Submit SALN?",html:"I certify that I have reviewed the information in this SALN and that the information submitted is my declaration.",icon:"warning",showCancelButton:true,confirmButtonText:"I certify and submit"});if(!confirmation.isConfirmed)return;setSaving(true);try{const saved=await salnApi.submit(selected.id,selected.status==="FOR_CORRECTION");setSelected(saved);setDraft({...saved});await loadList();await Swal.fire("SALN submitted","Your declaration is now read-only while under review.","success");}catch(error){await Swal.fire("Unable to submit",errorText(error),"error");}finally{setSaving(false);}};
  const discard=async()=>{if(!selected||selected.status!=="DRAFT")return;const result=await Swal.fire({title:"Discard draft?",text:"This draft has not been filed and will be deleted.",icon:"warning",showCancelButton:true,confirmButtonText:"Discard"});if(!result.isConfirmed)return;try{await salnApi.discard(selected.id);resetToNew();await loadList();}catch(error){await Swal.fire("Unable to discard",errorText(error),"error");}};
  return <div className={modalStyles.Modal}>
   <div className={modalStyles.modalContent}>
    <div className={modalStyles.modalHeader}>
     <h2 className={modalStyles.mainTitle}>Statement of Assets, Liabilities and Net Worth</h2>
    </div>
    <div className={modalStyles.modalBody}>
     <div className={styles.workspace}>
    <header><div><p className={styles.eyebrow}>Employee declaration</p><h1>Statement of Assets, Liabilities and Net Worth</h1><p>CSC 2025 prescribed information • Sensitive and access-restricted</p></div><button type="button" disabled={saving} onClick={()=>void startNew()}>New SALN</button></header>
    <section className={styles.history}><h2>Filing history</h2>{loading?<p>Loading…</p>:records.length===0?<p>No SALN records yet.</p>:<div className={styles.recordGrid}>{records.map(record=><button type="button" key={record.id} className={selected?.id===record.id?styles.activeRecord:""} onClick={()=>void open(record.id)}><strong>{record.filingType} {record.salnYear}</strong><span>{record.status.replaceAll("_"," ")}</span><small>Due {record.dueDate} • Version {record.versionNo}</small></button>)}</div>}</section>
    {corrections.some(item=>!item.resolved)&&<section className={styles.corrections}><h2>Corrections requested</h2>{corrections.filter(item=>!item.resolved).map(item=><p key={item.id}><strong>{item.section||"SALN"}{item.field?` — ${item.field}`:""}:</strong> {item.message}</p>)}</section>}
    {selected&&<button type="button" className={styles.add} onClick={()=>void previewPdf(selected.id)}>Preview / print CSC SALN PDF</button>}
    {formOpen&&<form onSubmit={save} className={styles.form}>
      <fieldset disabled={!editable||saving}><legend>1. Filing and declarant information</legend><div className={styles.fields}>
        <label>Filing type<select value={draft.filingType} onChange={e=>{const filingType=e.target.value as SalnDraft["filingType"];setField("filingType",filingType);if(filingType==="ANNUAL")setField("referenceDate",`${draft.salnYear}-12-31`);}}><option value="ASSUMPTION">Assumption</option><option value="ANNUAL">Annual</option><option value="SEPARATION">Exit / Separation</option></select></label>
        <label>SALN year<input type="number" min="1900" max="2200" value={draft.salnYear} onChange={e=>{const year=Number(e.target.value);setField("salnYear",year);if(draft.filingType==="ANNUAL")setField("referenceDate",`${year}-12-31`);}} required /></label>
        <label>Reference / as-of date<input type="date" value={draft.referenceDate} onChange={e=>setField("referenceDate",e.target.value)} disabled={draft.filingType==="ANNUAL"} required /></label>
        <label>Position<input value={draft.declarantPosition} onChange={e=>setField("declarantPosition",e.target.value)} /></label>
        <label>Agency / office<input value={draft.declarantAgencyOffice} onChange={e=>setField("declarantAgencyOffice",e.target.value)} /></label>
        <label>Office address<textarea value={draft.declarantOfficeAddress} onChange={e=>setField("declarantOfficeAddress",e.target.value)} /></label>
      </div></fieldset>
      <fieldset disabled={!editable||saving}><legend>2. Spouse and children</legend><div className={styles.fields}><label>Spouse full name<input value={draft.spouseFullName} onChange={e=>setField("spouseFullName",e.target.value)} /></label><label>Spouse position<input value={draft.spousePosition} onChange={e=>setField("spousePosition",e.target.value)} /></label><label>Spouse agency / office<input value={draft.spouseAgencyOffice} onChange={e=>setField("spouseAgencyOffice",e.target.value)} /></label><label>Spouse office address<input value={draft.spouseOfficeAddress} onChange={e=>setField("spouseOfficeAddress",e.target.value)} /></label><label>Filing arrangement<select value={draft.filingMode} onChange={e=>setField("filingMode",e.target.value as SalnDraft["filingMode"])}><option value="JOINT">Joint filing</option><option value="SEPARATE">Separate filing</option><option value="NOT_APPLICABLE">Not applicable</option></select></label><label>Other spouse names, if legally applicable<textarea value={draft.multipleSpouses} onChange={e=>setField("multipleSpouses",e.target.value)} /></label></div>
        <h3>Unmarried children below 18 living in the household</h3>{draft.dependents.map((row,index)=><div className={styles.row} key={index}><input aria-label="Child name" placeholder="Name" value={row.name} onChange={e=>setField("dependents",replaceAt(draft.dependents,index,{...row,name:e.target.value}))} required/><input aria-label="Relationship" placeholder="Relationship" value={row.relationship} onChange={e=>setField("dependents",replaceAt(draft.dependents,index,{...row,relationship:e.target.value}))} required/><input aria-label="Age" type="number" min="0" max="17" value={row.age} onChange={e=>setField("dependents",replaceAt(draft.dependents,index,{...row,age:Number(e.target.value)}))} required/><button type="button" onClick={()=>setField("dependents",draft.dependents.filter((_,i)=>i!==index))}>Remove</button></div>)}<button type="button" className={styles.add} onClick={()=>setField("dependents",[...draft.dependents,{name:"",relationship:"CHILD",age:0}])}>Add child</button>
      </fieldset>
      <fieldset disabled={!editable||saving}>
        <legend>3. Real properties</legend>
        {draft.realProperties.map((row,index)=><div className={styles.assetRow} key={index}>
          <Owner ownerType={row.ownerType} ownerName={row.ownerName} onType={value=>setField("realProperties",replaceAt(draft.realProperties,index,{...row,ownerType:value}))} onName={value=>setField("realProperties",replaceAt(draft.realProperties,index,{...row,ownerName:value}))}/>
          <input placeholder="Description" value={row.description} onChange={e=>setField("realProperties",replaceAt(draft.realProperties,index,{...row,description:e.target.value}))} required/>
          <input placeholder="Kind" value={row.kind} onChange={e=>setField("realProperties",replaceAt(draft.realProperties,index,{...row,kind:e.target.value}))} required/>
          <input placeholder="Exact location" value={row.exactLocation} onChange={e=>setField("realProperties",replaceAt(draft.realProperties,index,{...row,exactLocation:e.target.value}))} required/>
          <MoneyInput label="Assessed value" value={row.assessedValue} onChange={value=>setField("realProperties",replaceAt(draft.realProperties,index,{...row,assessedValue:value}))}/>
          <MoneyInput label="Current fair market value" value={row.fairMarketValue} onChange={value=>setField("realProperties",replaceAt(draft.realProperties,index,{...row,fairMarketValue:value}))}/>
          <input type="number" min="1000" max="2200" placeholder="Acquisition year" value={row.acquisitionYear} onChange={e=>setField("realProperties",replaceAt(draft.realProperties,index,{...row,acquisitionYear:Number(e.target.value)}))} required/>
          <input placeholder="Acquisition mode" value={row.acquisitionMode} onChange={e=>setField("realProperties",replaceAt(draft.realProperties,index,{...row,acquisitionMode:e.target.value}))}/>
          <MoneyInput label="Acquisition cost" value={row.acquisitionCost} onChange={value=>setField("realProperties",replaceAt(draft.realProperties,index,{...row,acquisitionCost:value}))}/>
          <button type="button" onClick={()=>setField("realProperties",draft.realProperties.filter((_,i)=>i!==index))}>Remove</button>
        </div>)}
        <button className={styles.add} type="button" onClick={()=>setField("realProperties",[...draft.realProperties,emptyReal()])}>Add real property</button>
      </fieldset>
      <fieldset disabled={!editable||saving}><legend>4. Personal properties</legend>{draft.personalProperties.map((row,index)=><div className={styles.assetRow} key={index}><Owner ownerType={row.ownerType} ownerName={row.ownerName} onType={value=>setField("personalProperties",replaceAt(draft.personalProperties,index,{...row,ownerType:value}))} onName={value=>setField("personalProperties",replaceAt(draft.personalProperties,index,{...row,ownerName:value}))}/><input placeholder="Description" value={row.description} onChange={e=>setField("personalProperties",replaceAt(draft.personalProperties,index,{...row,description:e.target.value}))} required/><input type="number" placeholder="Acquisition year" value={row.acquisitionYear} onChange={e=>setField("personalProperties",replaceAt(draft.personalProperties,index,{...row,acquisitionYear:Number(e.target.value)}))}/><MoneyInput label="Acquisition cost / amount" value={row.acquisitionCost} onChange={value=>setField("personalProperties",replaceAt(draft.personalProperties,index,{...row,acquisitionCost:value}))}/><button type="button" onClick={()=>setField("personalProperties",draft.personalProperties.filter((_,i)=>i!==index))}>Remove</button></div>)}<button className={styles.add} type="button" onClick={()=>setField("personalProperties",[...draft.personalProperties,emptyPersonal()])}>Add personal property</button></fieldset>
      <fieldset disabled={!editable||saving}><legend>5. Liabilities</legend>{draft.liabilities.map((row,index)=><div className={styles.assetRow} key={index}><Owner ownerType={row.ownerType} ownerName={row.ownerName} onType={value=>setField("liabilities",replaceAt(draft.liabilities,index,{...row,ownerType:value}))} onName={value=>setField("liabilities",replaceAt(draft.liabilities,index,{...row,ownerName:value}))}/><input placeholder="Nature" value={row.nature} onChange={e=>setField("liabilities",replaceAt(draft.liabilities,index,{...row,nature:e.target.value}))} required/><input placeholder="Creditor" value={row.creditorName} onChange={e=>setField("liabilities",replaceAt(draft.liabilities,index,{...row,creditorName:e.target.value}))} required/><MoneyInput label="Outstanding balance" value={row.outstandingBalance} onChange={value=>setField("liabilities",replaceAt(draft.liabilities,index,{...row,outstandingBalance:value}))}/><button type="button" onClick={()=>setField("liabilities",draft.liabilities.filter((_,i)=>i!==index))}>Remove</button></div>)}<button className={styles.add} type="button" onClick={()=>setField("liabilities",[...draft.liabilities,emptyLiability()])}>Add liability</button></fieldset>
      <fieldset disabled={!editable||saving}><legend>6. Business interests and financial connections</legend><label className={styles.check}><input type="checkbox" checked={draft.businessInterestsNone} onChange={e=>{setField("businessInterestsNone",e.target.checked);if(e.target.checked)setField("businessInterests",[]);}}/> I/We do not have any business interest or financial connection.</label>{!draft.businessInterestsNone&&<>{draft.businessInterests.map((row,index)=><div className={styles.assetRow} key={index}><Owner ownerType={row.ownerType} ownerName={row.ownerName} onType={value=>setField("businessInterests",replaceAt(draft.businessInterests,index,{...row,ownerType:value}))} onName={value=>setField("businessInterests",replaceAt(draft.businessInterests,index,{...row,ownerName:value}))}/><input placeholder="Entity / enterprise" value={row.entityName} onChange={e=>setField("businessInterests",replaceAt(draft.businessInterests,index,{...row,entityName:e.target.value}))} required/><input placeholder="Business address" value={row.businessAddress} onChange={e=>setField("businessInterests",replaceAt(draft.businessInterests,index,{...row,businessAddress:e.target.value}))} required/><input placeholder="Nature of interest" value={row.nature} onChange={e=>setField("businessInterests",replaceAt(draft.businessInterests,index,{...row,nature:e.target.value}))} required/><input type="date" value={row.dateAcquired} onChange={e=>setField("businessInterests",replaceAt(draft.businessInterests,index,{...row,dateAcquired:e.target.value}))}/><button type="button" onClick={()=>setField("businessInterests",draft.businessInterests.filter((_,i)=>i!==index))}>Remove</button></div>)}<button className={styles.add} type="button" onClick={()=>setField("businessInterests",[...draft.businessInterests,emptyBusiness()])}>Add business interest</button></>}</fieldset>
      <fieldset disabled={!editable||saving}><legend>7. Relatives in government</legend><label className={styles.check}><input type="checkbox" checked={draft.relativesInGovernmentNone} onChange={e=>{setField("relativesInGovernmentNone",e.target.checked);if(e.target.checked)setField("governmentRelatives",[]);}}/> I/We do not know of any relative in government within the required degree.</label>{!draft.relativesInGovernmentNone&&<>{draft.governmentRelatives.map((row,index)=><div className={styles.assetRow} key={index}><input placeholder="Name" value={row.name} onChange={e=>setField("governmentRelatives",replaceAt(draft.governmentRelatives,index,{...row,name:e.target.value}))} required/><input placeholder="Relationship" value={row.relationship} onChange={e=>setField("governmentRelatives",replaceAt(draft.governmentRelatives,index,{...row,relationship:e.target.value}))} required/><input placeholder="Position" value={row.position} onChange={e=>setField("governmentRelatives",replaceAt(draft.governmentRelatives,index,{...row,position:e.target.value}))} required/><input placeholder="Agency / office and address" value={row.agencyOfficeAddress} onChange={e=>setField("governmentRelatives",replaceAt(draft.governmentRelatives,index,{...row,agencyOfficeAddress:e.target.value}))} required/><button type="button" onClick={()=>setField("governmentRelatives",draft.governmentRelatives.filter((_,i)=>i!==index))}>Remove</button></div>)}<button className={styles.add} type="button" onClick={()=>setField("governmentRelatives",[...draft.governmentRelatives,{name:"",relationship:"",position:"",agencyOfficeAddress:""}])}>Add relative</button></>}</fieldset>
      <fieldset disabled={!editable||saving}><legend>8. Review and certification</legend><div className={styles.totals}><span>Real property<strong>{money(computed.real)}</strong></span><span>Personal property<strong>{money(computed.personal)}</strong></span><span>Total assets<strong>{money(computed.assets)}</strong></span><span>Total liabilities<strong>{money(computed.liabilities)}</strong></span><span>Net worth<strong>{money(computed.net)}</strong></span></div><div className={styles.fields}><label>Government ID type<input value={draft.governmentIdType} onChange={e=>setField("governmentIdType",e.target.value)}/></label><label>ID number<input value={draft.governmentIdNo} onChange={e=>setField("governmentIdNo",e.target.value)}/></label><label>Date issued<input type="date" value={draft.governmentIdDateIssued} onChange={e=>setField("governmentIdDateIssued",e.target.value)}/></label></div><label className={styles.check}><input type="checkbox" checked={draft.certificationAccepted} onChange={e=>setField("certificationAccepted",e.target.checked)}/> I certify that I have reviewed this information and that it is my declaration.</label></fieldset>
      <div className={styles.actions}>{editable&&<button type="submit" disabled={saving}>{saving?"Saving…":"Save draft"}</button>}{selected&&editable&&<button type="button" className={styles.primary} disabled={saving} onClick={()=>void submit()}>{selected.status==="FOR_CORRECTION"?"Resubmit corrected SALN":"Submit SALN"}</button>}{selected?.status==="DRAFT"&&<button type="button" className={styles.danger} onClick={()=>void discard()}>Discard draft</button>}{selected&&!editable&&<p>This filed version is read-only. Current status: <strong>{selected.status.replaceAll("_"," ")}</strong>.</p>}</div>
    </form>}
     </div>
    </div>
   </div>
  </div>;
}

function Owner({ownerType,ownerName,onType,onName}:{ownerType:"DECLARANT"|"SPOUSE"|"CHILD";ownerName:string;onType:(value:"DECLARANT"|"SPOUSE"|"CHILD")=>void;onName:(value:string)=>void}){return <><select aria-label="Owner" value={ownerType} onChange={e=>onType(e.target.value as "DECLARANT"|"SPOUSE"|"CHILD")}><option value="DECLARANT">Declarant</option><option value="SPOUSE">Spouse</option><option value="CHILD">Child</option></select>{ownerType!=="DECLARANT"&&<input aria-label="Owner name" placeholder="Owner name" value={ownerName} onChange={e=>onName(e.target.value)} required/>}</>}
function MoneyInput({label,value,onChange}:{label:string;value:string|number;onChange:(value:string)=>void}){return <input aria-label={label} title={label} placeholder={label} type="number" min="0" step="0.01" value={value} onChange={e=>onChange(e.target.value)} required/>}
